name : CI
on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: Windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Node.js dependencies
        run: npm install
      - name: Run Node.js build
        run: npm run build
      - name: Run Node.js tests
        run: |
          node tests/             